const stardewFish = [
  "Pufferfish",
  "Anchovy",
  "Tuna",
  "Sardine",
  "Bream",
  "Largemouth Bass",
  "Smallmouth Bass",
  "Rainbow Trout",
  "Salmon",
  "Walleye",
  "Perch",
  "Carp",
  "Catfish",
  "Pike",
  "Sunfish",
  "Red Mullet",
  "Herring",
  "Eel",
  "Octopus",
  "Red Snapper",
  "Squid",
  "Seaweed",
  "Green Algae",
  "Sea Cucumber",
  "Super Cucumber",
  "Ghostfish",
  "White Algae",
  "Stonefish",
  "Crimsonfish",
  "Angler",
  "Ice Pip",
  "Lava Eel",
  "Legend",
  "Sandfish",
  "Scorpion Carp",
  "Flounder",
  "Midnight Carp",
  "Clam",
  "Mutant Carp",
  "Sturgeon",
  "Tiger Trout",
  "Bullhead",
  "Tilapia",
  "Chub",
  "Dorado",
  "Albacore",
  "Shad",
  "Lingcod",
  "Halibut",
  "Lobster",
  "Crayfish",
  "Crab",
  "Cockle",
  "Mussel",
  "Shrimp",
  "Snail",
  "Periwinkle",
  "Oyster",
  "Woodskip",
  "Glacierfish",
  "Void Salmon",
  "Slimejack",
  "Midnight Squid",
  "Spook Fish",
  "Blobfish",
  "Stingray",
  "Lionfish",
  "Blue Discus",
  "River Jelly",
  "Cave Jelly",
  "Sea Jelly",
  "Goby",
];
export default stardewFish;
